export const languageNames = {
  cs: "Czech",
  nl: "Dutch",
  fr: "French",
  fi: "Finnish",
  el: "Greek",
  id: "Indonesian",
  it: "Italian",
  lt: "Lithuanian",
  lv: "Latvian",
  zh: "Mandarin",
  pl: "Polish",
  ro: "Romanian",
  es: "Spanish",
  sv: "Swedish",
  tr: "Turkish",
  uk: "Ukrainian",
};
